#### Author: Ernie Sumoso

1-Find the cosine similarity between two given documents

Input:

text1='Taj Mahal is a tourist place in India'

text2='Great Wall of China is a tourist place in china'

Desired Output :


[[1.         0.45584231]

 [0.45584231 1.        ]]

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

def get_cosine_sim_between_2_docs(doc1, doc2):
    docs = [doc1, doc2]
    v = TfidfVectorizer()
    tfidf = v.fit_transform(docs)
    pairwise_similarity = tfidf * tfidf.T
    return pairwise_similarity.A

text1='Taj Mahal is a tourist place in India'
text2='Great Wall of China is a tourist place in china'
get_cosine_sim_between_2_docs(text1, text2)

array([[1.        , 0.30069751],
       [0.30069751, 1.        ]])

2-Compute the soft cosine similarity of the given documents

Hint: Soft Cosine Similarity

Input :

doc_soup = "Soup is a primarily liquid food, generally served warm or hot (but may be cool or cold), that is made by combining ingredients of meat or vegetables with stock, juice, water, or another liquid. "

doc_noodles = "Noodles are a staple food in many cultures. They are made from unleavened dough which is stretched, extruded, or rolled flat and cut into one of a variety of shapes."

doc_dosa = "Dosa is a type of pancake from the Indian subcontinent, made from a fermented batter. It is somewhat similar to a crepe in appearance. Its main ingredients are rice and black gram."

doc_trump = "Mr. Trump became president after winning the political election. Though he lost the support of some republican friends, Trump is friends with President Putin"

doc_election = "President Trump says Putin had no political interference is the election outcome. He says it was a witchhunt by political parties. He claimed President Putin is a friend who had nothing to do with the election"

doc_putin = "Post elections, Vladimir Putin became President of Russia. President Putin had served as the Prime Minister earlier in his political career"
Desired Output :


0.5842470477718544

In [2]:
doc_soup = "Soup is a primarily liquid food, generally served warm or hot (but may be cool or cold), that is made by combining ingredients of meat or vegetables with stock, juice, water, or another liquid."
doc_noodles = "Noodles are a staple food in many cultures. They are made from unleavened dough which is stretched, extruded, or rolled flat and cut into one of a variety of shapes."
doc_dosa = "Dosa is a type of pancake from the Indian subcontinent, made from a fermented batter. It is somewhat similar to a crepe in appearance. Its main ingredients are rice and black gram."
doc_trump = "Mr. Trump became president after winning the political election. Though he lost the support of some republican friends, Trump is friends with President Putin"
doc_election = "President Trump says Putin had no political interference is the election outcome. He says it was a witchhunt by political parties. He claimed President Putin is a friend who had nothing to do with the election"
doc_putin = "Post elections, Vladimir Putin became President of Russia. President Putin had served as the Prime Minister earlier in his political career"

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def get_soft_cosine_similarity(docs):
    v = TfidfVectorizer(stop_words='english')
    matrix = v.fit_transform(docs)
    concept_vector = np.mean(matrix.toarray(), axis=0)
    soft_cosine_sim = np.dot(matrix.toarray(), concept_vector) / (np.linalg.norm(matrix.toarray(), axis=1) * np.linalg.norm(concept_vector))
    print(soft_cosine_sim)
    return np.mean(soft_cosine_sim)

docs = [doc_soup, doc_noodles, doc_dosa, doc_trump, doc_election, doc_putin]
get_soft_cosine_similarity(docs)

[0.39530021 0.36658059 0.36504666 0.56948246 0.59257285 0.55709011]


0.4743454773391967

3- How to create bigrams using Gensim’s Phraser ?

Q. Create bigrams from the given texts using Gensim library’s Phrases

Input :

documents = ["the mayor of new york was there", "new york mayor was present"]

Desired Output:

 ['the', 'mayor', 'of', 'new york', 'was', 'there']
 
['new york', 'mayor', 'was', 'present']

In [19]:
from nltk import word_tokenize
from gensim.models import Phrases
from gensim.models.phrases import Phraser

def get_bigrams_from_gensim_phraser(docs):
    tokenized_docs = [word_tokenize(doc) for doc in docs]
    bigram = Phrases(tokenized_docs, min_count=1, threshold=2, delimiter=' ')
    bigram_phraser = Phraser(bigram)
    for doc in tokenized_docs:
        tokens_ = bigram_phraser[doc]
        print(tokens_)
        
docs = ["the mayor of new york was there", "new york mayor was present"]
get_bigrams_from_gensim_phraser(docs)

['the', 'mayor', 'of', 'new york', 'was', 'there']
['new york', 'mayor', 'was', 'present']


4- How to create bigrams, trigrams using ngrams ?

Extract all bigrams , trigrams using ngrams of nltk library

Input

Sentences="Machine learning is a neccessary field in today's world. Data science can do wonders . Natural Language Processing is how machines understand text "

Desired Output:

Bigrams are [('machine', 'learning'), ('learning', 'is'), ('is', 'a'), ('a', 'neccessary'), ('neccessary', 'field'), ('field', 'in'), ('in', "today's"), ("today's", 'world.'), ('world.', 'data'), ('data', 'science'), ('science', 'can'), ('can', 'do'), ('do', 'wonders'), ('wonders', '.'), ('.', 'natural'), ('natural', 'language'), ('language', 'processing'), ('processing', 'is'), ('is', 'how'), ('how', 'machines'), ('machines', 'understand'), ('understand', 'text')]

 Trigrams are [('machine', 'learning', 'is'), ('learning', 'is', 'a'), ('is', 'a', 'neccessary'), ('a', 'neccessary', 'field'), ('neccessary', 'field', 'in'), ('field', 'in', "today's"), ('in', "today's", 'world.'), ("today's", 'world.', 'data'), ('world.', 'data', 'science'), ('data', 'science', 'can'), ('science', 'can', 'do'), ('can', 'do', 'wonders'), ('do', 'wonders', '.'), ('wonders', '.', 'natural'), ('.', 'natural', 'language'), ('natural', 'language', 'processing'), ('language', 'processing', 'is'), ('processing', 'is', 'how'), ('is', 'how', 'machines'), ('how', 'machines', 'understand'), ('machines', 'understand', 'text')]

In [42]:
from nltk.collocations import BigramCollocationFinder
from nltk.metrics import BigramAssocMeasures
from nltk.collocations import TrigramCollocationFinder
from nltk.metrics import TrigramAssocMeasures
from nltk import sent_tokenize
import nltk

def get_bigrams_trigrams_from_text(text, n=100):
    sentences = sent_tokenize(text)
    words = []
    for sentence in sentences:
        words += map(str.lower, nltk.WhitespaceTokenizer().tokenize(sentence))
    
    bcf = BigramCollocationFinder.from_words(words)
    print("Bigrams are:")
    display(bcf.nbest(BigramAssocMeasures.likelihood_ratio, n))

    tcf = TrigramCollocationFinder.from_words(words)
    print("\nTrigrams are:")
    display(tcf.nbest(TrigramAssocMeasures.likelihood_ratio, n))

text = "Machine learning is a neccessary field in today's world. Data science can do wonders . Natural Language Processing is how machines understand text "
get_bigrams_trigrams_from_text(text)

Bigrams are:


[('.', 'natural'),
 ('a', 'neccessary'),
 ('can', 'do'),
 ('data', 'science'),
 ('do', 'wonders'),
 ('field', 'in'),
 ('how', 'machines'),
 ('in', "today's"),
 ('language', 'processing'),
 ('machine', 'learning'),
 ('machines', 'understand'),
 ('natural', 'language'),
 ('neccessary', 'field'),
 ('science', 'can'),
 ("today's", 'world.'),
 ('understand', 'text'),
 ('wonders', '.'),
 ('world.', 'data'),
 ('is', 'a'),
 ('is', 'how'),
 ('learning', 'is'),
 ('processing', 'is')]


Trigrams are:


[('.', 'natural', 'language'),
 ('a', 'neccessary', 'field'),
 ('can', 'do', 'wonders'),
 ('data', 'science', 'can'),
 ('do', 'wonders', '.'),
 ('field', 'in', "today's"),
 ('how', 'machines', 'understand'),
 ('in', "today's", 'world.'),
 ('machines', 'understand', 'text'),
 ('natural', 'language', 'processing'),
 ('neccessary', 'field', 'in'),
 ('science', 'can', 'do'),
 ("today's", 'world.', 'data'),
 ('wonders', '.', 'natural'),
 ('world.', 'data', 'science'),
 ('is', 'a', 'neccessary'),
 ('is', 'how', 'machines'),
 ('language', 'processing', 'is'),
 ('learning', 'is', 'a'),
 ('machine', 'learning', 'is'),
 ('processing', 'is', 'how')]